// <auto-generated />
namespace Handle_KNSER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Event_Member : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Event_Member));
        
        string IMigrationMetadata.Id
        {
            get { return "201512311012305_Event_Member"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
