// <auto-generated />
namespace Handle_KNSER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Participant_DB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Participant_DB));
        
        string IMigrationMetadata.Id
        {
            get { return "201601021045543_Participant_DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
